script execution interrupted
Co-Authored-By: Ryan Kurtz <5378554+ryanmkurtz@users.noreply.github.com>
Co-Authored-By: Ghidra1 <48333017+ghidra1@users.noreply.github.com>
Co-Authored-By: GhidorahRex <49028988+ghidorahrex@users.noreply.github.com>
Co-Authored-By: dev747368 <48332326+dev747368@users.noreply.github.com>
Co-Authored-By: ghizard <50744617+ghizard@users.noreply.github.com>
Co-Authored-By: Linus Torvalds <1024025+torvalds@users.noreply.github.com>
Co-Authored-By: E R Cool <31413933+eclipsesrcool@users.noreply.github.com>
Co-Authored-By: Krishna Chaiatanya <ekrishnachaitanya2004@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,14 @@
 #!/bin/sh
-# This script was automatically generated by ACR v2.1.4
+# This script was automatically generated by thc-ghidra v2.1.4
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
-# @repo:   git clone https://github.com/radare/acr
+# @repo:   git clone https://github.com/byt3n33dl3/thc-ghidra
 
 [ -z "${AWK}" ] && AWK=awk
 do_remove() {
-if [ "${ACR_RMFILES}" ]; then
+if [ "${thc-ghidra_RMFILES}" ]; then
   printf "cleaning temporally files... "
-  rm -f ${ACR_RMFILES}
+  rm -f ${thc-ghidra_RMFILES}
   echo "done"
 fi
 }
@@ -132,7 +132,7 @@ create_environ() {
 : ${DATADIR:="${SPREFIX}/share"}
 : ${INFODIR:="${DATADIR}/info"}
 : ${MANDIR:="${DATADIR}/man"}
-: ${DOCDIR:="${DATADIR}/doc/radare2"}
+: ${DOCDIR:="${DATADIR}/doc/byt3n33dl32"}
 : ${LOCALSTATEDIR:="${SPREFIX}/var"}
 for A in `echo ${PATH} | sed -e 's,:, ,g'` ; do
   [ -e "$A"/ginstall ] && : ${INSTALL:="$A"/ginstall} && break
@@ -145,12 +145,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2' ; VERSION='5.9.9' ; VERSION_MAJOR=5; VERSION_MINOR=9; VERSION_PATCH=9; VERSION_NUMBER=50909; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='byt3n33dl32' ; VERSION='5.9.9' ; VERSION_MAJOR=5; VERSION_MINOR=9; VERSION_PATCH=9; VERSION_NUMBER=50909; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-5.9.9 to adapt to many kinds of systems.
+'configure' configures byt3n33dl32-5.9.9 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -173,7 +173,7 @@ Installation directories:
 Fine tuning of the installation directories:
   --bindir=DIR           user executables [EPREFIX/bin]
   --datadir=DIR          read-only architecture-independent data [PREFIX/share]
-  --docdir=DIR           documentation directory [DATADIR/doc/radare2]
+  --docdir=DIR           documentation directory [DATADIR/doc/byt3n33dl32]
   --includedir=DIR       C header files [PREFIX/include]
   --infodir=DIR          info documentation [DATADIR/info]
   --libexecdir=DIR       program executables [EPREFIX/libexec]
@@ -266,7 +266,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.9.9"
 	exit 0
 fi
-echo "radare2-5.9.9 configuration script done with acr v2.1.4.
+echo "byt3n33dl32-5.9.9 configuration script done with thc-ghidra v2.1.4.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -294,7 +294,7 @@ case $flag in
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
-echo "PKGNAME:     radare2"
+echo "PKGNAME:     byt3n33dl32"
 echo "VERSION:     5.9.9"
 echo "AUTHOR:      pancake"
 echo "EMAIL:       pancake@nopcode.org"
@@ -307,7 +307,7 @@ echo "FLAGS:       --disable-debugger --with-sysmagic --disable-threads --disabl
 	exit 0
 	;;
 --cache-file)
-	# ignored: acr have no cache
+	# ignored: thc-ghidra have no cache
 	;;
 --build)
 	BUILD="$value"; split_host BUILD ; ;;
@@ -396,8 +396,8 @@ esac
 # MAIN #
 take_environ
 split_host BUILD HOST TARGET
-[ -z "$ACRHOOK" ] && ACRHOOK=./configure.hook
-[ -e "$ACRHOOK" ] && . ${ACRHOOK}
+[ -z "$thc-ghidraHOOK" ] && thc-ghidraHOOK=./configure.hook
+[ -e "$thc-ghidraHOOK" ] && . ${thc-ghidraHOOK}
 
 while : ; do
 [ -z "$1" ] && break
@@ -418,7 +418,7 @@ ocho "checking target system type... ${TARGET}"
 [ -n "${prefix}" ] && PREFIX="${prefix}"
 ocho "checking for working directories... ${WODIS}"
 ocho "using prefix '${PREFIX}'"
-ACR_RMFILES=" test.c a.out a.exe"
+thc-ghidra_RMFILES=" test.c a.out a.exe"
 
 COMPILER=CC
 ochof "checking for c compiler... "
@@ -987,20 +987,20 @@ for A in ${ENVWORDS} ; do
 done
 SEDFLAGS="${SEDFLAGS}'"
 for A in ./config-user.mk libr/include/r_userconf.h pkgcfg/r_core.pc  ; do # SUBDIRS
-if [ -f "${VPATH}/${A}.acr" ]; then
+if [ -f "${VPATH}/${A}.thc-ghidra" ]; then
   SD_TARGET=${A}
  else
   if [ -d "${VPATH}/${A}" ]; then
    SD_TARGET=${A}/Makefile
    mkdir -p ${A}
   else
-   echo "ERROR: Cannot find ${VPATH}/${A}.acr" >&2
+   echo "ERROR: Cannot find ${VPATH}/${A}.thc-ghidra" >&2
    exit 1
   fi
  fi
  ocho "creating ${SD_TARGET}"
 [ "${VPATH}" != '.' ] &&  mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
- cat ${VPATH}/${SD_TARGET}.acr | \
+ cat ${VPATH}/${SD_TARGET}.thc-ghidra | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
 
 for A in ${ENVWORDS}; do
